// <auto-generated />
using System;
using Desafio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio.Apresentacao.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507194537_001")]
    partial class _001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desafio.Entities.Status", b =>
                {
                    b.Property<int>("int_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("int_id"));

                    b.Property<bool>("sta_ativo")
                        .HasColumnType("bit");

                    b.Property<string>("str_nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("int_id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Desafio.Entities.Tarefa", b =>
                {
                    b.Property<int>("int_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("int_id"));

                    b.Property<DateTime>("dat_vencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("int_status")
                        .HasColumnType("int");

                    b.Property<bool>("str_descricao")
                        .HasColumnType("bit");

                    b.Property<string>("str_titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("int_id");

                    b.ToTable("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
